"use client";

/* eslint-disable @typescript-eslint/no-explicit-any -- contributions / community how-to
   entries are loosely-typed crowdsource blobs; typed as any to match the prototype. */
/* eslint-disable react/no-unescaped-entities -- how-to copy is ported verbatim (contains apostrophes). */

import { useEffect, useState } from "react";
import { S } from "@/lib/styles";
import { HOWTOS } from "@/data/howtos";
import { HOWTO_VARIANTS } from "@/data/howto-variants";
import { DEVICES } from "@/data/devices";
import type { ModelNode } from "@/lib/types";
import LocalOnly from "@/components/common/LocalOnly";
import ResourceList from "./ResourceList";
import type { MyDevices } from "./DevicesModal";
import { OutdatedFlag } from "./_review";
import { VoteControl } from "@/components/contribute/VoteControl";
import StepHelp from "./StepHelp";
import type { AISeed } from "@/components/ai/AIModal";
import { fetchHowtos, type HowtoView } from "@/lib/contribute/vote-state";
import { COMMUNITY_HOWTOS } from "@/data/community-content";
import { connectAndSignIn } from "@/lib/wallet";
import { CONTRIBUTOR_TERMS } from "@/lib/contribute/terms";

interface HowToProps {
  node: ModelNode;
  contributions: any;
  setContributions: (c: any) => void;
  myDevices?: MyDevices;
  saveDevices?: (d: MyDevices) => void;
  openAI?: (seed: AISeed) => void;
}

export default function HowTo({ node, contributions, setContributions, myDevices, saveDevices, openAI }: HowToProps) {
  const [open, setOpen] = useState(false);
  const [platform, setPlatform] = useState("");
  const [steps, setSteps] = useState("");
  const [src, setSrc] = useState("");
  const [msg, setMsg] = useState<string | null>(null);          // inline submit feedback
  const [override, setOverride] = useState<string | null>(null);   // per-step device override
  const [community, setCommunity] = useState<HowtoView[]>([]);  // live community how-tos (backend)

  const seed = HOWTOS[node.id] || null;
  const vcfg = HOWTO_VARIANTS[node.id] || null;     // device-variant config for this move
  const axis = vcfg ? vcfg.axis : null;             // phone | desktop | browser

  // selected device: per-step override wins, else your global profile, else generic
  const profileKey = axis && myDevices ? (myDevices as any)[axis] : null;
  const selKey = override !== null ? override : (vcfg && profileKey && vcfg.variants[profileKey] ? profileKey : null);
  const variant = vcfg && selKey ? vcfg.variants[selKey] : null;
  const deviceList = axis ? (DEVICES[axis] || []) : [];

  // live community how-tos for this node (empty if backend is unavailable → graceful)
  const loadHowtos = async () => { setCommunity(await fetchHowtos(node.id)); };
  useEffect(() => {
    let ok = true;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- async network fetch; setState lands after the round-trip, scoped to [node.id]
    setCommunity([]); setMsg(null);
    fetchHowtos(node.id).then((h) => { if (ok) setCommunity(h); }).catch(() => { if (ok) setCommunity([]); });
    return () => { ok = false; };
  }, [node.id]);

  const submit = async () => {
    const lines = steps.split("\n").map((s) => s.trim()).filter(Boolean);
    if (!platform.trim() || lines.length === 0) return;
    setMsg(null);
    const body = { kind: "howto", targetId: node.id, platform: platform.trim(), steps: lines, ...(src.trim() ? { src: { url: src.trim() } } : {}) };
    try {
      const res = await fetch("/api/contribute/submit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      if (res.status === 401) { try { await connectAndSignIn(); } catch {} setMsg("Connect a wallet to contribute, then submit again."); return; }
      if (res.status === 403) { const { error } = await res.json().catch(() => ({})); setMsg(error || "Your wallet isn't eligible to contribute yet."); return; }
      if (res.status === 400) { const { error } = await res.json().catch(() => ({})); setMsg(error || "Please check the fields."); return; }
      if (!res.ok) { setMsg("Couldn't submit — try again."); return; }
      setPlatform(""); setSteps(""); setSrc("");
      await loadHowtos();
    } catch { setMsg("Network error — try again."); }
  };

  // The seed how-to is ALSO a DB contribution (id "howto:<nodeId>") so it's votable —
  // but it's already rendered from the static HOWTOS below, so drop it from the live
  // community list to avoid showing it twice.
  const seedHowtoId = "howto:" + node.id;
  // Tier 2 — the community-static layer: VERIFIED community how-tos baked into the
  // build (regenerated by the bake script). Render as verified cards.
  const bakedHowtos = COMMUNITY_HOWTOS[node.id] || [];
  const bakedIds = new Set(bakedHowtos.map((h) => h.id));
  // Drop the seed how-to (it's already rendered above) AND any baked id (rendered
  // just below) from the live list, so nothing double-renders.
  const communityHowtos = community.filter((h) => h.id !== seedHowtoId && !bakedIds.has(h.id));
  const hasAny = seed || variant || bakedHowtos.length || communityHowtos.length;

  return (
    <div style={{ marginTop: 16 }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 5 }}>
        <div style={{ ...S.sectLabel, color: "#5fd3c8", margin: 0 }}>HOW TO DO THIS</div>
        <span style={{ display: "flex", gap: 5, alignItems: "center" }}>
          <span style={{ ...S.commTag, borderColor: "#2a5d63", color: "#5fd3c8" }}>community-maintained</span>
          <OutdatedFlag nodeId={node.id} contributions={contributions} setContributions={setContributions} />
        </span>
      </div>
      <div style={{ ...S.tiny, marginTop: 5, marginBottom: 8 }}>
        Steps change as apps and laws change — kept current by contributors. Verify against the official sources below.
      </div>

      {/* device selector: dropdown (scales to many devices); ★ saves as your default */}
      {vcfg && (
        <div style={S.devRow}>
          <span style={{ ...S.tiny, flexShrink: 0 }}>YOUR DEVICE</span>
          <select value={selKey || ""} onChange={(e) => setOverride(e.target.value === "" ? null : e.target.value)} style={S.devSelect}>
            <option value="">Generic (any device)</option>
            {deviceList.filter((d) => vcfg.variants[d.k]).map((d) => (
              <option key={d.k} value={d.k}>{d.label}{profileKey === d.k ? " ★ (my default)" : ""}</option>
            ))}
            {deviceList.filter((d) => !vcfg.variants[d.k]).map((d) => (
              <option key={d.k} value={d.k} disabled>{d.label} — no steps yet (contribute!)</option>
            ))}
          </select>
          {selKey && selKey !== profileKey && saveDevices && (
            <button style={S.devSave} onClick={() => saveDevices({ ...(myDevices || ({} as MyDevices)), [axis as keyof MyDevices]: selKey })}>★ set as my default</button>
          )}
        </div>
      )}
      {vcfg && <LocalOnly compact />}

      {!hasAny && (
        <div style={S.howtoEmpty}>
          No how-to yet for this move. <b style={{ color: "#d4dae6" }}>Be the first to write one.</b>
        </div>
      )}

      {/* device-exact steps when a variant is selected; otherwise the generic starter */}
      {variant ? (
        <div style={{ ...S.howtoCard, borderLeftColor: "#5fd3c8" }}>
          <div style={S.howtoHead}>
            <span style={{ color: "#fff", fontSize: 12.5, fontWeight: 600 }}>{variant.label} — exact steps</span>
            <span style={{ ...S.commTag, borderColor: "#2a4d2a", color: "#8ce29a" }}>verified seed</span>
          </div>
          <ol style={S.howtoSteps}>{variant.steps.map((s, i) => <li key={i}>{s}</li>)}</ol>
          <div style={{ marginTop: 6 }}><VoteControl nodeId={"howto:" + node.id} /></div>
          <StepHelp node={node} steps={variant.steps} device={variant.label} openAI={openAI} />
          <ResourceList nodeId={node.id} contributions={contributions} setContributions={setContributions} />
        </div>
      ) : seed && (
        <div style={S.howtoCard}>
          <div style={S.howtoHead}>
            <span style={{ color: "#fff", fontSize: 12.5, fontWeight: 600 }}>{seed.platform}</span>
            <span style={{ ...S.commTag, borderColor: "#2a4d2a", color: "#8ce29a" }}>starter guide</span>
          </div>
          <ol style={S.howtoSteps}>{seed.steps.map((s, i) => <li key={i}>{s}</li>)}</ol>
          <div style={{ marginTop: 6 }}><VoteControl nodeId={"howto:" + node.id} /></div>
          <StepHelp node={node} steps={seed.steps} openAI={openAI} />
          <ResourceList nodeId={node.id} contributions={contributions} setContributions={setContributions} />
        </div>
      )}

      {vcfg && deviceList.some((d) => !vcfg.variants[d.k]) && (
        <div style={{ ...S.tiny, margin: "2px 0 8px", color: "#969eb0" }}>
          Missing your exact device? Add steps for it below — that's how this stays accurate.
        </div>
      )}

      {/* community-static layer (tier 2): VERIFIED community how-tos baked into the
          build. Verified → the source is a clickable link, each carries a VoteControl. */}
      {bakedHowtos.map((h, i) => (
        <div key={h.id || "baked-" + i} style={S.howtoCard}>
          <div style={S.howtoHead}>
            <span style={{ color: "#fff", fontSize: 12.5, fontWeight: 600 }}>{h.platform}</span>
            <span style={{ ...S.commTag, borderColor: "#2a4d2a", color: "#8ce29a" }}>community ✓ verified</span>
          </div>
          <ol style={S.howtoSteps}>{h.steps.map((s, j) => <li key={j}>{s}</li>)}</ol>
          {h.src?.url && (
            <div style={{ ...S.tiny, marginTop: 4 }}>
              <a href={h.src.url} target="_blank" rel="noopener noreferrer" style={{ color: "#5fd3c8", wordBreak: "break-all" }}>source ↗</a>
            </div>
          )}
          <div style={{ marginTop: 6 }}><VoteControl nodeId={h.id} /></div>
          <StepHelp node={node} steps={h.steps} device={h.platform} openAI={openAI} />
        </div>
      ))}

      {/* live community how-tos from the backend — each carries its own VoteControl */}
      {communityHowtos.map((h, i) => {
        const verified = h.badge === "verified";
        const url = h.payload.src?.url;
        return (
          <div key={h.id || i} style={S.howtoCard}>
            <div style={S.howtoHead}>
              <span style={{ color: "#fff", fontSize: 12.5, fontWeight: 600 }}>{h.payload.platform}</span>
              <span style={{ ...S.commTag, borderColor: verified ? "#2a4d2a" : "#313846", color: verified ? "#8ce29a" : "#9aa0b5" }}>{verified ? "community ✓ verified" : "⏳ in review"}</span>
            </div>
            <ol style={S.howtoSteps}>{h.payload.steps.map((s: string, j: number) => <li key={j}>{s}</li>)}</ol>
            {url && (
              <div style={{ ...S.tiny, marginTop: 4 }}>
                {/* PHISHING GUARD: a claimed source is a clickable link ONLY after the maintainer verifies it; otherwise plain text */}
                {verified
                  ? <a href={url} target="_blank" rel="noopener noreferrer" style={{ color: "#5fd3c8", wordBreak: "break-all" }}>source ↗</a>
                  : <>claimed source (verify): <span style={{ color: "#9aa0b5", wordBreak: "break-all" }}>{url}</span></>}
              </div>
            )}
            <div style={{ marginTop: 6 }}><VoteControl nodeId={h.id} /></div>
            <StepHelp node={node} steps={h.payload.steps} device={h.payload.platform} openAI={openAI} />
          </div>
        );
      })}

      {!open
        ? <button style={S.addSrc} onClick={() => setOpen(true)}>＋ add / improve a how-to (your device, your OS version)</button>
        : (
          <div style={S.suggestBox}>
            <div style={S.tiny}>Contribute device-exact steps. Name the device AND version — paths move between releases. <b style={{color:'#f0c468'}}>Submissions enter community review and stay marked 'in review' until verified.</b> {CONTRIBUTOR_TERMS}</div>
            <input value={platform} onChange={(e) => setPlatform(e.target.value)} placeholder="device + version (e.g. Samsung One UI 8, iOS 26.4, Xiaomi HyperOS 2)" style={S.input} />
            <textarea value={steps} onChange={(e) => setSteps(e.target.value)} placeholder={"one step per line:\nSettings → Privacy\nTurn off Allow Tracking\n…"} style={{ ...S.input, minHeight: 90, resize: "vertical", fontFamily: "inherit" }} />
            <input value={src} onChange={(e) => setSrc(e.target.value)} placeholder="source URL (optional but encouraged)" style={S.input} />
            <div style={{ display: "flex", gap: 6 }}>
              <button style={S.goalBtn} onClick={submit}>submit how-to</button>
              <button style={S.clearBtn} onClick={() => setOpen(false)}>cancel</button>
            </div>
            {msg && <div style={{ ...S.tiny, color: "#f0c468" }}>{msg}</div>}
          </div>
        )}
    </div>
  );
}
