"use client";

/* eslint-disable @typescript-eslint/no-explicit-any -- contributions is a loosely-typed
   crowdsource blob; typed as any to match the prototype. */

import { useEffect, useState } from "react";
import { S } from "@/lib/styles";
import { RTYPE_C, RTYPE_BADGE } from "@/data/ui-maps";
import { RESOURCES } from "@/data/resources";
import { affiliate } from "@/data/affiliate";
import { VoteControl } from "@/components/contribute/VoteControl";
import { fetchResources, type ResourceView } from "@/lib/contribute/vote-state";
import { COMMUNITY_RESOURCES } from "@/data/community-content";
import { connectAndSignIn } from "@/lib/wallet";
import { CONTRIBUTOR_TERMS } from "@/lib/contribute/terms";

interface ResourceListProps {
  nodeId: string;
  contributions: any;
  setContributions?: (c: any) => void;
}

const AFFILIATE_DISCLOSURE =
  "Some links may be affiliate links — they help fund the project at no extra cost to you. We list free/open options first wherever one exists.";

export default function ResourceList({ nodeId, setContributions }: ResourceListProps) {
  const seed = RESOURCES[nodeId] || [];

  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const [url, setUrl] = useState("");
  const [forStep, setForStep] = useState("");
  const [resourceType, setResourceType] = useState<"link" | "product">("link");
  const [msg, setMsg] = useState<string | null>(null);            // inline submit feedback
  const [community, setCommunity] = useState<ResourceView[]>([]); // live community resources (backend)

  // live community resources for this node (empty if backend is unavailable → graceful)
  const loadResources = async () => { setCommunity(await fetchResources(nodeId)); };
  useEffect(() => {
    let ok = true;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- async network fetch; setState lands after the round-trip, scoped to [nodeId]
    setCommunity([]); setMsg(null);
    fetchResources(nodeId).then((r) => { if (ok) setCommunity(r); }).catch(() => { if (ok) setCommunity([]); });
    return () => { ok = false; };
  }, [nodeId]);

  // Seed resources are ALSO DB contributions (ids "res:<nodeId>:<i>") so they're votable —
  // but they're already rendered from the static RESOURCES below, so drop them from the
  // live community list to avoid showing them twice.
  // Tier 2 — the community-static layer: VERIFIED community resources baked into the
  // build (regenerated by the bake script). Render as verified cards.
  const bakedResources = COMMUNITY_RESOURCES[nodeId] || [];
  const bakedIds = new Set(bakedResources.map((r) => r.id));
  // Drop seed contributions (rendered above) AND any baked id (rendered just below)
  // from the live list, so nothing double-renders.
  const communityResources = community.filter((r) => !r.id.startsWith("res:" + nodeId + ":") && !bakedIds.has(r.id));
  const hasAny = seed.length || bakedResources.length || communityResources.length;

  const submit = async () => {
    if (!/^https?:\/\//.test(url) || !name.trim()) return;
    setMsg(null);
    const body = {
      kind: "resource",
      targetId: nodeId,
      name: name.trim(),
      url: url.trim(),
      resourceType,
      ...(forStep.trim() ? { forStep: forStep.trim() } : {}),
    };
    try {
      const res = await fetch("/api/contribute/submit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      if (res.status === 401) { try { await connectAndSignIn(); } catch {} setMsg("Connect a wallet to contribute, then submit again."); return; }
      if (res.status === 403) { const { error } = await res.json().catch(() => ({})); setMsg(error || "Your wallet isn't eligible to contribute yet."); return; }
      if (res.status === 400) { const { error } = await res.json().catch(() => ({})); setMsg(error || "Please check the fields."); return; }
      if (!res.ok) { setMsg("Couldn't submit — try again."); return; }
      setName(""); setUrl(""); setForStep(""); setResourceType("link"); setOpen(false);
      await loadResources();
    } catch { setMsg("Network error — try again."); }
  };

  return (
    <div style={S.resWrap}>
      <div style={S.resHead}>WHAT TO USE</div>
      {!hasAny && <div style={S.tiny}>No tools listed yet — add one below.</div>}

      {/* seed resources from RESOURCES (static, local-first) — clickable affiliate links + a VoteControl */}
      {seed.map((r: any, i: number) => (
        <div key={"seed-" + i} style={{ ...S.resItem, display: "block" }}>
          <a href={affiliate(r.url)} target="_blank" rel="noopener noreferrer sponsored" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
            {r.imageUrl && (
              // eslint-disable-next-line @next/next/no-img-element -- resource thumbnails may be externally hosted Amazon product images; next/image would require broad remote host config.
              <img
                src={r.imageUrl}
                alt={r.imageAlt || r.name}
                loading="lazy"
                style={{ width: 64, height: 64, objectFit: "cover", borderRadius: 12, border: "1px solid #1d2430", background: "#0b0f16", flexShrink: 0 }}
              />
            )}
            <span style={{ ...S.resType, color: RTYPE_C[r.type] || "#9aa0b5", borderColor: "#1d2430" }}>{RTYPE_BADGE[r.type] || "LINK"}{r.price ? " " + r.price : ""}</span>
            <span style={{ flex: 1, minWidth: 0 }}>
              <span style={{ color: "#e4e8f0", fontSize: 12.5 }}>{r.name}</span>
              {r.forStep && <span style={{ display: "block", ...S.tiny, marginTop: 1 }}>{r.forStep}</span>}
            </span>
            <span style={{ opacity: 0.4 }}>↗</span>
          </a>
          <div style={{ marginTop: 6 }}><VoteControl nodeId={"res:" + nodeId + ":" + i} /></div>
        </div>
      ))}

      {/* community-static layer (tier 2): VERIFIED community resources baked into the
          build. Verified → the URL is a clickable affiliate link, each has a VoteControl. */}
      {bakedResources.map((r, i) => (
        <div key={r.id || "baked-" + i} style={{ ...S.resItem, display: "block" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}>
            <span style={{ ...S.resType, color: "#9aa0b5", borderColor: "#1d2430" }}>{r.resourceType === "product" ? "BUY" : "LINK"}</span>
            <span style={{ color: "#e4e8f0", fontSize: 12.5 }}>{r.name}</span>
            <span style={{ ...S.commTag, borderColor: "#2a4d2a", color: "#8ce29a" }}>community ✓ verified</span>
          </div>
          {r.forStep && <div style={{ ...S.tiny, marginTop: 2 }}>{r.forStep}</div>}
          <div style={{ ...S.tiny, marginTop: 3 }}>
            <a href={affiliate(r.url)} target="_blank" rel="noopener noreferrer sponsored" style={{ color: "#5fd3c8", wordBreak: "break-all" }}>{r.url} ↗</a>
          </div>
          <div style={{ marginTop: 6 }}><VoteControl nodeId={r.id} /></div>
        </div>
      ))}

      {/* live community resources from the backend — each carries its own VoteControl */}
      {communityResources.map((r, i) => {
        const verified = r.badge === "verified";
        const commercial = !!r.reviewMeta?.commercial;
        const affiliateUrl = r.reviewMeta?.affiliate?.url;
        const href = affiliateUrl ? affiliate(affiliateUrl) : affiliate(r.payload.url);
        return (
          <div key={r.id || i} style={{ ...S.resItem, display: "block" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}>
              <span style={{ ...S.resType, color: "#9aa0b5", borderColor: "#1d2430" }}>{r.payload.resourceType === "product" ? "BUY" : "LINK"}</span>
              <span style={{ color: "#e4e8f0", fontSize: 12.5 }}>{r.payload.name}</span>
              <span style={{ ...S.commTag, borderColor: verified ? "#2a4d2a" : "#313846", color: verified ? "#8ce29a" : "#9aa0b5" }}>{verified ? "community ✓ verified" : "⏳ in review"}</span>
              {verified && affiliateUrl && <span style={{ ...S.commTag, borderColor: "#3a2a1a", color: "#f0a868" }}>affiliate</span>}
            </div>
            {r.payload.forStep && <div style={{ ...S.tiny, marginTop: 2 }}>{r.payload.forStep}</div>}
            <div style={{ ...S.tiny, marginTop: 3 }}>
              {/* PHISHING GUARD: a submitted URL is clickable ONLY after the maintainer verifies it; otherwise plain text */}
              {verified
                ? <a href={href} target="_blank" rel="noopener noreferrer sponsored" style={{ color: "#5fd3c8", wordBreak: "break-all" }}>{r.payload.url} ↗</a>
                : <>URL (in review): <span style={{ color: "#9aa0b5", wordBreak: "break-all" }}>{r.payload.url}</span></>}
            </div>
            {/* commercial marker / disclosure driven off reviewMeta, NOT the submitter's resourceType */}
            {commercial && !verified && (
              <div style={{ ...S.tiny, marginTop: 3, color: "#f0c468" }}>⏳ commercial — under review</div>
            )}
            {(commercial || affiliateUrl) && (
              <div style={{ ...S.tiny, marginTop: 3, color: "#8893a4" }}>{AFFILIATE_DISCLOSURE}</div>
            )}
            <div style={{ marginTop: 6 }}><VoteControl nodeId={r.id} /></div>
          </div>
        );
      })}

      {setContributions && (!open
        ? <button style={S.addRes} onClick={() => setOpen(true)}>＋ suggest a tool / product</button>
        : (
          <div style={S.suggestBox}>
            <div style={S.tiny}>Suggest a resource. <b style={{color:'#f0c468'}}>It enters community review — the link stays unclickable until verified.</b> Affiliate links are disclosed as such. {CONTRIBUTOR_TERMS}</div>
            <div style={{ display: "flex", gap: 6 }}>
              <button style={{ ...S.goalBtn, opacity: resourceType === "link" ? 1 : 0.5 }} onClick={() => setResourceType("link")}>Helpful link</button>
              <button style={{ ...S.goalBtn, opacity: resourceType === "product" ? 1 : 0.5 }} onClick={() => setResourceType("product")}>Product / service</button>
            </div>
            <input value={name} onChange={(e) => setName(e.target.value)} placeholder="name (e.g. Reflectacles)" style={S.input} />
            <input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://…" style={S.input} />
            <input value={forStep} onChange={(e) => setForStep(e.target.value)} placeholder="what it's for (optional)" style={S.input} />
            <div style={{ display: "flex", gap: 6 }}>
              <button style={S.goalBtn} onClick={submit}>submit</button>
              <button style={S.clearBtn} onClick={() => setOpen(false)}>cancel</button>
            </div>
            {msg && <div style={{ ...S.tiny, color: "#f0c468" }}>{msg}</div>}
          </div>
      ))}

      {(seed.some((r: any) => r.type === "product" || r.type === "service") || bakedResources.some((r) => r.resourceType === "product") || communityResources.some((r) => r.reviewMeta?.commercial)) && (
        <div style={{ ...S.tiny, marginTop: 6, color: "#8893a4" }}>
          {AFFILIATE_DISCLOSURE}
        </div>
      )}
    </div>
  );
}
