import type { CSSProperties } from "react";

export const mono = "ui-monospace, 'SF Mono', Menlo, monospace";

export const S: Record<string, CSSProperties> = {
  app: { position: "fixed", inset: 0, background: "#070809", color: "#d4dae6", fontFamily: "'Georgia', serif", display: "flex", flexDirection: "column", overflow: "hidden" },
  header: { padding: "14px 22px 10px", borderBottom: "1px solid #1a1f29", flexShrink: 0 },
  h1: { fontFamily: mono, fontSize: 22, fontWeight: 700, letterSpacing: 2, color: "#fff", margin: 0 },
  subtitle: { fontSize: 12.5, color: "#969eb0", fontStyle: "italic" },
  statline: { fontFamily: mono, fontSize: 10.5, color: "#8893a4", marginTop: 5, letterSpacing: 0.3 },
  tabs: { display: "flex", gap: 2, padding: "0 18px", borderBottom: "1px solid #1a1f29", flexShrink: 0, flexWrap: "nowrap", overflowX: "auto", overflowY: "hidden" },
  tab: { background: "none", border: "none", color: "#8893a4", fontFamily: mono, fontSize: 11, letterSpacing: 1, padding: "10px 14px", cursor: "pointer", borderBottom: "2px solid transparent", flexShrink: 0, whiteSpace: "nowrap" },
  tabActive: { color: "#fff", borderBottom: "2px solid #5fd3c8" },
  body: { display: "flex", flex: 1, minHeight: 0 },
  left: { width: 234, flexShrink: 0, borderRight: "1px solid #1a1f29", padding: 16, overflowY: "auto", display: "flex", flexDirection: "column", background: "#090b10" },
  center: { flex: 1, minWidth: 0, position: "relative", background: "#070809" },
  right: { width: 340, flexShrink: 0, borderLeft: "1px solid #1a1f29", overflowY: "auto", paddingBottom: 90, background: "#090b10" },
  detailSheet: { position: "fixed", inset: 0, zIndex: 70, background: "#070809", overflowY: "auto", paddingBottom: 90, WebkitOverflowScrolling: "touch" },
  mobileToolbar: { display: "flex", alignItems: "center", gap: 8, padding: "8px 12px", borderBottom: "1px solid #1a1f29", flexShrink: 0, background: "#090b10" },
  toolBtn: { display: "inline-flex", alignItems: "center", gap: 6, background: "none", border: "1px solid #2a3340", color: "#d4dae6", borderRadius: 8, fontFamily: mono, fontSize: 12.5, padding: "8px 12px", cursor: "pointer", minHeight: 40, flexShrink: 0 },
  drawerScrim: { position: "fixed", inset: 0, zIndex: 65, background: "rgba(4,5,7,0.6)", backdropFilter: "blur(2px)" },
  drawer: { position: "fixed", top: 0, bottom: 0, left: 0, width: "84%", maxWidth: 320, zIndex: 66, background: "#090b10", borderRight: "1px solid #1a1f29", overflowY: "auto", padding: 16, display: "flex", flexDirection: "column", WebkitOverflowScrolling: "touch" },
  drawerHead: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  detailSheetBar: { position: "sticky", top: 0, zIndex: 1, display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", background: "rgba(7,8,9,0.92)", borderBottom: "1px solid #1a1f29", backdropFilter: "blur(4px)" },
  sheetBack: { display: "inline-flex", alignItems: "center", gap: 6, background: "none", border: "1px solid #2a3340", color: "#d4dae6", borderRadius: 8, fontFamily: mono, fontSize: 12.5, padding: "7px 12px", cursor: "pointer", minHeight: 40, flexShrink: 0 },
  placeholder: { padding: 30, color: "#8893a4", textAlign: "center", display: "flex", flexDirection: "column", alignItems: "center", marginTop: 60, fontSize: 14, lineHeight: 1.6 },
  ctrlLabel: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.1, color: "#8893a4", marginBottom: 10, textTransform: "uppercase" },
  input: { width: "100%", background: "#10141b", border: "1px solid #232a36", color: "#e4e8f0", padding: "7px 9px", fontFamily: mono, fontSize: 12.5, borderRadius: 3, outline: "none", boxSizing: "border-box" },
  chip: { display: "inline-flex", alignItems: "center", gap: 6, background: "#10141b", border: "1px solid", borderRadius: 20, padding: "4px 10px", fontSize: 11, color: "#d4dae6", cursor: "pointer", fontFamily: mono },
  tiny: { fontFamily: mono, fontSize: 10.5, color: "#8b94a6", lineHeight: 1.5 },
  clearBtn: { background: "none", border: "1px solid #313846", color: "#9aa0b5", padding: "5px 10px", borderRadius: 3, fontSize: 11, cursor: "pointer", fontFamily: mono, marginTop: 6 },
  canvasHint: { fontFamily: mono, fontSize: 10.5, color: "#7e8798", pointerEvents: "none" },
  zoomBtn: { width: 40, height: 40, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(13,16,22,0.92)", border: "1px solid #232a36", color: "#d4dae6", borderRadius: 8, fontSize: 17, cursor: "pointer", backdropFilter: "blur(3px)", lineHeight: 1 },
  wayTop: { position: "absolute", top: 12, left: 14, display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", maxWidth: "calc(100% - 28px)" },
  wayBtn: { background: "#10141b", border: "1px solid #2a5d63", color: "#5fd3c8", fontFamily: mono, fontSize: 11, padding: "5px 11px", borderRadius: 20, cursor: "pointer", letterSpacing: 0.3 },
  youAreHere: { display: "flex", alignItems: "center", gap: 7, background: "rgba(13,16,22,0.9)", border: "1px solid #232a36", borderRadius: 20, padding: "5px 6px 5px 11px", fontSize: 12.5, backdropFilter: "blur(4px)" },
  wayClose: { background: "none", border: "1px solid #232a36", color: "#969eb0", width: 18, height: 18, borderRadius: 9, cursor: "pointer", fontSize: 10, lineHeight: "1", display: "flex", alignItems: "center", justifyContent: "center" },
  breadcrumbs: { position: "absolute", top: 48, left: 14, display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap", maxWidth: "calc(100% - 28px)", background: "rgba(7,8,9,0.7)", padding: "4px 8px", borderRadius: 6, backdropFilter: "blur(3px)" },
  crumb: { background: "none", border: "none", color: "#9aa0b5", fontFamily: mono, fontSize: 10.5, cursor: "pointer", padding: "2px 4px", borderRadius: 3, maxWidth: 130, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  wayBottom: { position: "absolute", bottom: 10, left: 14, right: 14, display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" },
  solBtn: { background: "#10141b", border: "1px solid #232a36", color: "#9aa0b5", fontFamily: mono, fontSize: 10.5, padding: "6px 12px", borderRadius: 20, cursor: "pointer", letterSpacing: 0.3 },
  solBtnOn: { borderColor: "#8ce29a", color: "#8ce29a", background: "#0e1a12" },
  detail: { padding: 22 },
  kicker: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.4, color: "#969eb0" },
  closeBtn: { marginLeft: "auto", background: "none", border: "1px solid #232a36", color: "#969eb0", width: 22, height: 22, borderRadius: 4, cursor: "pointer", fontSize: 11, lineHeight: "1", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  searchResults: { marginTop: 6, display: "flex", flexDirection: "column", gap: 2, maxHeight: 200, overflowY: "auto", borderTop: "1px solid #1a1f29", paddingTop: 6 },
  searchHit: { display: "flex", alignItems: "center", gap: 7, background: "none", border: "none", color: "#d4dae6", fontSize: 12.5, fontFamily: "Georgia, serif", padding: "4px 5px", borderRadius: 3, cursor: "pointer", textAlign: "left", width: "100%" },
  howtoEmpty: { fontSize: 12.5, color: "#9aa0b5", background: "#0d1016", border: "1px dashed #232a36", borderRadius: 4, padding: "10px 12px", lineHeight: 1.5 },
  howtoCard: { background: "#0d1016", border: "1px solid #1d2430", borderLeft: "2px solid #2a5d63", borderRadius: 4, padding: "10px 12px", marginBottom: 7 },
  howtoHead: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  howtoSteps: { margin: 0, paddingLeft: 18, fontSize: 12.5, lineHeight: 1.65, color: "#d0d6e2", display: "flex", flexDirection: "column", gap: 4 },
  resWrap: { marginTop: 11, paddingTop: 10, borderTop: "1px solid #161b22" },
  resHead: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.2, color: "#8893a4", marginBottom: 6 },
  resItem: { display: "flex", alignItems: "center", gap: 8, background: "#10141b", border: "1px solid #1d2430", borderRadius: 4, padding: "7px 9px", margin: "4px 0", textDecoration: "none", lineHeight: 1.3 },
  resType: { fontFamily: mono, fontSize: 10, letterSpacing: 0.4, border: "1px solid", borderRadius: 2, padding: "1px 4px", flexShrink: 0, whiteSpace: "nowrap" },
  addRes: { background: "none", border: "1px dashed #313846", color: "#969eb0", padding: "6px", width: "100%", borderRadius: 3, fontSize: 11, cursor: "pointer", fontFamily: mono, marginTop: 5 },
  devRow: { display: "flex", flexWrap: "wrap", gap: 5, marginBottom: 9, alignItems: "center" },
  devChip: { background: "#10141b", border: "1px solid #232a36", color: "#9aa0b5", fontFamily: mono, fontSize: 10.5, padding: "4px 9px", borderRadius: 14, cursor: "pointer", letterSpacing: 0.2 },
  devChipOn: { borderColor: "#5fd3c8", color: "#5fd3c8", background: "#0e1a1e" },
  devSave: { background: "none", border: "none", color: "#f0c468", fontFamily: mono, fontSize: 10.5, cursor: "pointer", padding: "4px 4px", letterSpacing: 0.3 },
  tabPersonal: { background: "#0e1518", border: "1px solid #1d3336", color: "#5fd3c8", fontFamily: mono, fontSize: 11, letterSpacing: 1, padding: "8px 14px", borderRadius: 6, cursor: "pointer", flexShrink: 0, whiteSpace: "nowrap" },
  tabPersonalActive: { background: "#11242a", border: "1px solid #2a5d63", color: "#8fe8de", boxShadow: "0 0 0 1px #1d3336" },
  welcome: { padding: "6px 2px" },
  welcomeLabel: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.6, color: "#8893a4", margin: "18px 0 8px" },
  welcomeRow: { display: "flex", gap: 9, alignItems: "baseline", fontSize: 12.5, color: "#aab0be", lineHeight: 1.55, marginBottom: 7 },
  welcomeKey: { fontFamily: mono, fontSize: 10.5, color: "#5fd3c8", border: "1px solid #1d3336", borderRadius: 4, padding: "2px 7px", whiteSpace: "nowrap", flexShrink: 0 },
  welcomeBtn: { display: "block", width: "100%", textAlign: "left", background: "#10141b", border: "1px solid #2a5d63", color: "#5fd3c8", fontFamily: mono, fontSize: 11, padding: "10px 13px", borderRadius: 6, cursor: "pointer", marginBottom: 7, lineHeight: 1.45 },
  toast: { position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", background: "#0e1a12", border: "1px solid #2a4d2a", color: "#d4dae6", borderRadius: 8, padding: "10px 18px", fontSize: 14, zIndex: 90, boxShadow: "0 6px 24px rgba(0,0,0,.5)", maxWidth: "90vw" },
  freshStart: { background: "#0e1518", border: "1px solid #1d3336", borderLeft: "2px solid #5fd3c8", borderRadius: 6, padding: "14px 16px", margin: "0 0 22px" },
  fineToggle: { background: "none", border: "1px solid #2a2415", color: "#f0a868", fontFamily: mono, fontSize: 10.5, letterSpacing: 1, padding: "7px 11px", borderRadius: 5, cursor: "pointer", width: "100%", textAlign: "left" },
  warnTeaser: { background: "none", border: "none", color: "#d9b28a", fontSize: 11, cursor: "pointer", padding: 0, textAlign: "left" },
  triageBtn: { background: "#10141b", border: "1px solid #2a5d63", color: "#5fd3c8", fontFamily: mono, fontSize: 11, padding: "9px 14px", borderRadius: 5, cursor: "pointer", letterSpacing: 0.3 },
  aiPanel: { background: "#13100b", border: "1px solid #2a2415", borderLeft: "2px solid #f0a868", borderRadius: 6, padding: "13px 16px", margin: "0 0 24px" },
  aiLeakWarn: { background: "#170f0a", border: "1px solid #3a2415", borderRadius: 5, padding: "9px 12px", fontSize: 11, color: "#d9b28a", lineHeight: 1.55 },
  aiBtn: { background: "#1a130b", border: "1px solid #5a3d1a", color: "#f0a868", fontFamily: mono, fontSize: 11, padding: "7px 13px", borderRadius: 7, cursor: "pointer", letterSpacing: 0.3 },
  aiLauncher: { position: "fixed", bottom: 22, right: 22, zIndex: 60, display: "inline-flex", alignItems: "center", gap: 8, background: "#1d150c", border: "1px solid #6b4a1f", color: "#f5b878", borderRadius: 30, fontFamily: mono, fontSize: 12.5, fontWeight: 700, padding: "11px 18px", cursor: "pointer", boxShadow: "0 6px 22px rgba(0,0,0,.5), 0 0 0 1px rgba(240,168,104,.18)" },
  aiModal: { background: "#0d0b07", border: "1px solid #5a3d1a", borderRadius: 12, padding: 22, maxWidth: 580, width: "92vw", maxHeight: "85vh", overflowY: "auto" },
  aiHeroCta: { display: "inline-flex", alignItems: "center", gap: 8, background: "#1d150c", border: "1px solid #6b4a1f", color: "#f5b878", fontFamily: mono, fontSize: 12.5, fontWeight: 700, padding: "11px 18px", borderRadius: 30, boxShadow: "0 0 0 1px rgba(240,168,104,.12)", cursor: "pointer" },
  aiChatBox: { display: "flex", flexDirection: "column", gap: 7, maxHeight: 340, overflowY: "auto", padding: "4px 2px", margin: "2px 0 2px" },
  aiMsgUser: { alignSelf: "flex-end", maxWidth: "85%", background: "#1a2230", border: "1px solid #2a3550", borderRadius: "9px 9px 2px 9px", padding: "8px 11px", fontSize: 14, color: "#e4e8f0", lineHeight: 1.5 },
  aiMsgBot: { alignSelf: "flex-start", maxWidth: "92%", background: "#13100b", border: "1px solid #2a2415", borderRadius: "9px 9px 9px 2px", padding: "8px 11px", fontSize: 14, color: "#d4dae6", lineHeight: 1.55, whiteSpace: "pre-wrap" },
  aiMoveChip: { display: "inline-flex", alignItems: "center", background: "#0e1a1e", border: "1px solid #2a5d63", color: "#5fd3c8", borderRadius: 4, padding: "1px 7px", margin: "0 2px", fontSize: 12.5, cursor: "pointer", fontFamily: "inherit", lineHeight: 1.5 },
  localOnly: { display: "flex", gap: 7, alignItems: "flex-start", background: "#0e1a12", border: "1px solid #1d3324", borderRadius: 5, padding: "8px 11px", margin: "10px 0", fontSize: 11, color: "#9fb5a6", lineHeight: 1.5 },
  devSelect: { background: "#10141b", border: "1px solid #232a36", color: "#e4e8f0", fontFamily: mono, fontSize: 11, padding: "6px 9px", borderRadius: 5, cursor: "pointer", maxWidth: "100%", flex: 1, minWidth: 0 },
  pendingToggle: { background: "none", border: "1px dashed #4d3a1a", color: "#f0c468", padding: "6px 10px", width: "100%", borderRadius: 3, fontSize: 10.5, cursor: "pointer", fontFamily: mono, textAlign: "left", letterSpacing: 0.3 },
  pendingCard: { background: "#13110c", border: "1px solid #2a2415", borderLeft: "2px solid #f0c468", borderRadius: 4, padding: "10px 12px", margin: "6px 0" },
  reviewRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, flexWrap: "wrap", marginTop: 8, paddingTop: 7, borderTop: "1px solid #2a2415" },
  reviewBtn: { background: "#0d1016", border: "1px solid", borderRadius: 4, fontFamily: mono, fontSize: 10.5, padding: "4px 9px", cursor: "pointer", letterSpacing: 0.3 },
  detailH: { fontFamily: mono, fontSize: 17, color: "#fff", margin: "2px 0 0", lineHeight: 1.2, fontWeight: 700 },
  metaBadge: { fontFamily: mono, fontSize: 10.5, border: "1px solid #313846", color: "#9aa0b5", padding: "2px 7px", borderRadius: 20, letterSpacing: 0.4 },
  summary: { fontSize: 14, lineHeight: 1.65, color: "#dde2ec", margin: "8px 0 18px" },
  honesty: { background: "#0d1016", borderLeft: "2px solid", padding: "8px 11px", margin: "8px 0", borderRadius: "0 3px 3px 0" },
  costRow: { display: "flex", gap: 6, margin: "12px 0" },
  costCell: { flex: 1, background: "#10141b", border: "1px solid #1d2430", borderRadius: 3, padding: "6px 8px", textAlign: "center" },
  sectLabel: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.1, color: "#8893a4", marginBottom: 9, marginTop: 20, textTransform: "uppercase" },
  actorTag: { fontFamily: mono, fontSize: 10.5, background: "#15110d", border: "1px solid #3a2a1a", color: "#f0a868", padding: "2px 7px", borderRadius: 3 },
  relPill: { background: "#10141b", border: "1px solid", borderRadius: 3, padding: "4px 8px", fontSize: 11, color: "#d7dce6", cursor: "pointer", fontFamily: "Georgia, serif", textAlign: "left" },
  goalBtn: { width: "100%", background: "#0e1a1e", border: "1px solid #2a5d63", color: "#5fd3c8", padding: "9px", borderRadius: 3, fontSize: 12.5, cursor: "pointer", fontFamily: mono, marginTop: 10, letterSpacing: 0.5 },
  source: { display: "flex", alignItems: "center", gap: 8, background: "#10141b", border: "1px solid #1d2430", borderRadius: 3, padding: "7px 9px", margin: "5px 0", fontSize: 12.5, color: "#d4dae6", textDecoration: "none", lineHeight: 1.35 },
  srcKind: { fontFamily: mono, fontSize: 10, letterSpacing: 0.6, color: "#5fd3c8", border: "1px solid #234", borderRadius: 2, padding: "1px 4px", flexShrink: 0 },
  commTag: { fontFamily: mono, fontSize: 10, color: "#7fb2ff", border: "1px solid #2a3f5d", borderRadius: 2, padding: "1px 4px" },
  addSrc: { background: "none", border: "1px dashed #313846", color: "#969eb0", padding: "7px", width: "100%", borderRadius: 3, fontSize: 11, cursor: "pointer", fontFamily: mono, marginTop: 6 },
  suggestBox: { display: "flex", flexDirection: "column", gap: 6, background: "#0d1016", border: "1px solid #1d2430", borderRadius: 3, padding: 10, marginTop: 6 },
  threatWrap: { height: "100%", overflowY: "auto", padding: "22px 26px 90px" },
  threatIntro: { fontSize: 14, color: "#9aa0b5", lineHeight: 1.6, maxWidth: 720, marginBottom: 16 },
  threatGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(290px, 1fr))", gap: 16 },
  threatCard: { background: "#0d1016", border: "1px solid #1d2430", borderLeft: "2px solid #ff5c5c", borderRadius: 4, padding: 13, cursor: "pointer" },
  threatTitle: { fontFamily: mono, fontSize: 14, color: "#fff", margin: "8px 0 6px", lineHeight: 1.25 },
  threatResidual: { fontSize: 12.5, color: "#aab0be", lineHeight: 1.5, margin: "0 0 8px" },
  threatSortRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 16 },
  sortBtn: { background: "#10141b", border: "1px solid #232a36", color: "#9aa0b5", fontFamily: mono, fontSize: 10.5, padding: "5px 11px", borderRadius: 20, cursor: "pointer", letterSpacing: 0.3 },
  sortBtnOn: { borderColor: "#5fd3c8", color: "#5fd3c8", background: "#0e1a1e" },
  threatCardV2: { background: "#0c0f14", border: "1px solid #181d26", borderRadius: 8, padding: 17 },
  threatTitleV2: { fontFamily: mono, fontSize: 17, fontWeight: 700, color: "#fff", margin: 0, lineHeight: 1.3 },
  counterLabel: { fontFamily: mono, fontSize: 10, fontWeight: 600, letterSpacing: 1, color: "#6fc088" },
  counterChip: { display: "inline-flex", alignItems: "center", gap: 5, background: "#10141b", border: "1px solid #1f2530", borderRadius: 5, padding: "5px 9px", fontSize: 11, color: "#d0d6e2", cursor: "pointer", fontFamily: "Georgia, serif", textAlign: "left", lineHeight: 1.2 },
  residualV2: { fontSize: 11, color: "#9298a8", lineHeight: 1.5, margin: "0 0 8px", background: "#0a0d12", borderRadius: 5, padding: "8px 10px" },
  traceBtn: { background: "none", border: "none", color: "#5fd3c8", fontFamily: mono, fontSize: 10.5, cursor: "pointer", padding: 0, letterSpacing: 0.3 },
  counteredByLead: { background: "#0e1a12", border: "1px solid #1d2430", borderLeft: "2px solid #8ce29a", borderRadius: "0 4px 4px 0", padding: "10px 12px", margin: "10px 0 12px" },
  contribWrap: { height: "100%", overflowY: "auto", padding: "26px 30px 90px", maxWidth: 860 },
  contribP: { fontSize: 14, lineHeight: 1.7, color: "#b6bcc8", maxWidth: 680 },
  contribGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(210px,1fr))", gap: 12, margin: "22px 0" },
  ccard: { background: "#0d1016", border: "1px solid #1d2430", borderRadius: 4, padding: 15 },
  contribStats: { fontSize: 14, color: "#d4dae6", background: "#0d1016", border: "1px solid #1d2430", borderRadius: 4, padding: 14, lineHeight: 1.6 },
  redoBtn: { background: "none", border: "1px solid #2a5d63", color: "#5fd3c8", fontFamily: mono, fontSize: 10.5, letterSpacing: 0.6, padding: "5px 11px", borderRadius: 20, cursor: "pointer", marginRight: 4, flexShrink: 0, whiteSpace: "nowrap" },
  extCta: { display: "inline-flex", alignItems: "center", gap: 6, whiteSpace: "nowrap", background: "rgba(240,196,104,0.07)", border: "1px solid #4d3a1a", color: "#f0c468", fontFamily: mono, fontSize: 10.5, letterSpacing: 0.8, textTransform: "uppercase", padding: "6px 13px", borderRadius: 20, cursor: "pointer", textDecoration: "none" },
  /* onboarding */
  modalWrap: { position: "fixed", inset: 0, background: "rgba(4,5,7,0.86)", backdropFilter: "blur(3px)", zIndex: 50, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  modal: { width: 540, maxWidth: "100%", background: "#0c0f15", border: "1px solid #232a36", borderRadius: 8, padding: "22px 26px 24px", boxShadow: "0 30px 80px rgba(0,0,0,.6)" },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  skip: { background: "none", border: "none", color: "#8893a4", fontFamily: mono, fontSize: 11, cursor: "pointer", textDecoration: "underline" },
  progress: { height: 2, background: "#1a1f29", borderRadius: 2, overflow: "hidden", marginBottom: 20 },
  progressFill: { height: "100%", background: "#5fd3c8", transition: "width .3s" },
  modalQ: { fontFamily: mono, fontSize: 22, color: "#fff", margin: 0, lineHeight: 1.25, fontWeight: 700 },
  modalSub: { fontSize: 14, color: "#9aa0b5", lineHeight: 1.55, marginTop: 7 },
  optBtn: { display: "flex", alignItems: "center", gap: 11, background: "#10141b", border: "1px solid #1d2430", borderRadius: 5, padding: "12px 14px", cursor: "pointer", transition: "all .15s" },
  optBtnActive: { borderColor: "#5fd3c8", background: "#0e1a1e" },
  /* path view */
  pathWrap: { height: "100%", overflowY: "auto", padding: "22px 30px 90px", maxWidth: 880 },
  pathEmpty: { height: "100%", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", textAlign: "center", color: "#969eb0", padding: 30 },
  pathHero: { marginBottom: 24, paddingBottom: 18, borderBottom: "1px solid #1a1f29" },
  phaseHead: { display: "flex", alignItems: "center", gap: 12, marginBottom: 11 },
  phaseNum: { fontFamily: mono, fontSize: 26, color: "#2a323f", fontWeight: 700, lineHeight: 1 },
  pathItem: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, background: "#0d1016", border: "1px solid #1a1f29", borderLeft: "2px solid #1d2430", borderRadius: 5, padding: "11px 14px", cursor: "pointer", transition: "border-color .15s, background .15s" },
  pathSummary: { fontSize: 12.5, color: "#9aa0b5", lineHeight: 1.5, marginTop: 3, maxWidth: 520 },
  domTag: { fontFamily: mono, fontSize: 10, letterSpacing: 0.5, color: "#969eb0", border: "1px solid #232a36", borderRadius: 3, padding: "1px 5px" },
  miniTag: { fontFamily: mono, fontSize: 10.5, color: "#9aa0b5", border: "1px solid #1d2430", borderRadius: 3, padding: "2px 6px" },
  urgentTag: { fontFamily: mono, fontSize: 10.5, color: "#ff8c6b", border: "1px solid #3a2018", borderRadius: 20, padding: "2px 8px", whiteSpace: "nowrap" },
  pathFoot: { fontSize: 12.5, color: "#8b94a6", borderTop: "1px solid #1a1f29", paddingTop: 16, lineHeight: 1.55 },
  /* journeys */
  journeyWrap: { height: "100%", overflowY: "auto", padding: "22px 30px 90px", maxWidth: 860 },
  journeyHero: { marginBottom: 22, paddingBottom: 18, borderBottom: "1px solid #1a1f29" },
  journeyGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 14 },
  journeyCard: { textAlign: "left", background: "#0d1016", border: "1px solid #1d2430", borderRadius: 6, padding: 18, cursor: "pointer", display: "block", color: "inherit", fontFamily: "inherit" },
  journeyProgress: { height: 3, background: "#1a1f29", borderRadius: 3, overflow: "hidden", marginTop: 12 },
  journeyProgressFill: { height: "100%", background: "#5fd3c8", transition: "width .3s" },
  backLink: { background: "none", border: "none", color: "#969eb0", fontFamily: mono, fontSize: 11, letterSpacing: 0.5, cursor: "pointer", padding: 0, marginBottom: 14 },
  rampLine: {},
  stageHead: { display: "flex", alignItems: "center", gap: 11, marginBottom: 11 },
  stageDot: { width: 11, height: 11, borderRadius: 11, border: "2px solid #5fd3c8", flexShrink: 0 },
  journeyStep: { display: "flex", gap: 11, background: "#0d1016", border: "1px solid #1a1f29", borderRadius: 5, padding: "11px 13px", alignItems: "flex-start" },
  checkbox: { width: 19, height: 19, borderRadius: 5, border: "1.5px solid #3a4250", background: "transparent", color: "#070809", cursor: "pointer", flexShrink: 0, fontSize: 12.5, lineHeight: "1", display: "flex", alignItems: "center", justifyContent: "center", marginTop: 2 },
  checkboxOn: { background: "#5fd3c8", borderColor: "#5fd3c8", color: "#070809", fontWeight: 700 },
  pairBox: { display: "flex", gap: 9, alignItems: "flex-start", background: "#0a0d12", border: "1px dashed #2a3f3f", borderRadius: 5, padding: "8px 10px", marginTop: 8 },
  howLink: { background: "none", border: "none", color: "#5fd3c8", fontFamily: mono, fontSize: 10.5, cursor: "pointer", padding: 0, letterSpacing: 0.3 },
  journeyDone: { background: "#0e1a12", border: "1px solid #2a4d2a", borderRadius: 6, padding: 14, color: "#8ce29a", fontSize: 14, lineHeight: 1.6, marginTop: 6 },
  sectionLabel: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.1, color: "#8893a4", textTransform: "uppercase", margin: "20px 0 9px", paddingBottom: 6, borderBottom: "1px solid #15191f" },
  pbarWrap: { background: "#0d1016", border: "1px solid #1d2430", borderRadius: 6, padding: 16, marginBottom: 24 },
  pbarTrack: { position: "relative", height: 12, background: "linear-gradient(90deg,#1a0c0c,#15110d 50%,#0e1a12)", border: "1px solid #1d2430", borderRadius: 6, overflow: "hidden" },
  pbarFill: { position: "absolute", left: 0, top: 0, bottom: 0, borderRadius: 6, transition: "width .4s ease, background .4s" },
  pbarCeiling: { position: "absolute", right: "8%", top: -2, bottom: -2, width: 2, background: "repeating-linear-gradient(0deg,#5b6472,#5b6472 3px,transparent 3px,transparent 6px)" },
  whereNext: { background: "#0e1a1e", border: "1px solid #2a5d63", borderRadius: 6, padding: "11px 14px", marginBottom: 22, cursor: "pointer" },
  outWrap: { height: "100%", overflowY: "auto", padding: "22px 30px 90px", maxWidth: 940 },
  outHero: { marginBottom: 24, paddingBottom: 18, borderBottom: "1px solid #1a1f29" },
  outSectLabel: { fontFamily: mono, fontSize: 10.5, fontWeight: 600, letterSpacing: 1.1, color: "#8893a4", textTransform: "uppercase", margin: "20px 0 9px" },
  personaGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(210px, 1fr))", gap: 13, marginBottom: 18 },
  personaCard: { textAlign: "left", background: "#0d1016", border: "1px solid #1d2430", borderRadius: 7, padding: 17, cursor: "pointer", color: "inherit", fontFamily: "inherit" },
  lookSheet: { background: "#0b0e13", border: "1px solid #232a36", borderRadius: 8, padding: 18, marginBottom: 10 },
  lookItem: { display: "flex", alignItems: "center", gap: 10, background: "#10141b", border: "1px solid #1a1f29", borderRadius: 5, padding: "10px 13px", cursor: "pointer" },
  catGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))", gap: 14 },
  catCard: { background: "#0d1016", border: "1px solid #1d2430", borderRadius: 7, padding: 15 },
  catItemBtn: { background: "none", border: "none", color: "#d4dae6", fontFamily: "Georgia, serif", fontSize: 14, cursor: "pointer", padding: 0, display: "block", marginBottom: 4 },
  catShopLink: { display: "flex", alignItems: "center", gap: 7, background: "#10141b", border: "1px solid #1d2430", borderRadius: 4, padding: "6px 9px", margin: "4px 0", fontSize: 12.5, color: "#d4dae6", textDecoration: "none" },
  outFoot: { fontSize: 12.5, color: "#8b94a6", borderTop: "1px solid #1a1f29", paddingTop: 16, marginTop: 28, lineHeight: 1.6, maxWidth: 720 },
  itemImg: { width: "100%", background: "#0a0d12", borderBottom: "1px solid #161b22", overflow: "hidden", position: "relative" },
  itemImgFallback: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: mono, fontSize: 10.5, letterSpacing: 1, opacity: 0.5 },
  personaGridV2: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: 14, marginBottom: 18 },
  personaCardV2: { textAlign: "left", background: "#0d1016", border: "1px solid #1d2430", borderRadius: 8, padding: 0, cursor: "pointer", color: "inherit", fontFamily: "inherit", overflow: "hidden" },
  personaHero: { position: "relative", display: "grid", gridTemplateColumns: "1fr 1fr 1fr", background: "#070809", borderBottom: "1px solid #1a1f29" },
  personaHeroCell: { borderRight: "1px solid #11151b" },
  personaIconBadge: { position: "absolute", top: 8, right: 8, fontSize: 17, background: "rgba(7,8,9,0.7)", borderRadius: 16, width: 30, height: 30, display: "flex", alignItems: "center", justifyContent: "center", backdropFilter: "blur(3px)" },
  lookItemGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))", gap: 11 },
  lookCard: { background: "#10141b", border: "1px solid #1a1f29", borderRadius: 6, overflow: "hidden", cursor: "pointer" },
  catGridV2: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(190px, 1fr))", gap: 13 },
  productCard: { background: "#0d1016", border: "1px solid #1d2430", borderRadius: 7, overflow: "hidden" },
  productName: { background: "none", border: "none", color: "#fff", fontFamily: "Georgia, serif", fontSize: 14, cursor: "pointer", padding: 0, textAlign: "left", display: "block" },
  productShop: { display: "flex", alignItems: "center", gap: 6, background: "#10141b", border: "1px solid #1d2430", borderRadius: 4, padding: "5px 8px", fontSize: 11, color: "#d4dae6", textDecoration: "none" },
};
