import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const sub = JSON.parse(readFileSync(join(__dirname, "..", "data", "graph-subset.json"), "utf8"));

describe("graph-subset.json (generated by sync.mjs)", () => {
  it("has all 33 threats", () => {
    expect(Object.keys(sub.threats).length).toBe(33);
  });
  it("every threat's counters resolve to a bundled move", () => {
    for (const t of Object.values(sub.threats) as { counters: string[] }[]) {
      for (const mid of t.counters) expect(sub.moves[mid], mid).toBeTruthy();
    }
  });
  it("a known threat carries its real counters (T-BROKER)", () => {
    expect(sub.threats["T-BROKER"].counters).toContain("data-broker-removal");
  });
});
