import howtos from "./community-howtos.json";
import resources from "./community-resources.json";
import sources from "./community-sources.json";
import regions from "./community-regions.json";
import type { CommunityHowto, CommunityResource, CommunitySource, CommunityRegion } from "@/lib/contribute/community-bake";

/** The community-static layer — verified community how-tos/resources/sources/regions baked
 *  from the DB (regenerated by scripts/bake-contributions.mjs). Empty until the first
 *  bake with verified community content. Read alongside the seed data. */
export const COMMUNITY_HOWTOS = howtos as Record<string, CommunityHowto[]>;
export const COMMUNITY_RESOURCES = resources as Record<string, CommunityResource[]>;
export const COMMUNITY_SOURCES = sources as Record<string, CommunitySource[]>;
export const COMMUNITY_REGIONS = regions as Record<string, CommunityRegion[]>;
